# Generated by Django 3.0.6 on 2020-08-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=254)),
                ('book_cover_url', models.URLField(max_length=500)),
                ('book_url', models.URLField(max_length=500)),
                ('view', models.CharField(max_length=100)),
                ('published_time', models.CharField(max_length=100)),
                ('user_count', models.CharField(max_length=100)),
                ('ranking', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('book_brief_info', models.CharField(max_length=100)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Genre')),
            ],
        ),
    ]
