# Generated by Django 3.0.6 on 2020-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_books_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_brief_one',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
