# Generated by Django 3.0.6 on 2020-08-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_books_book_brief_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_brief_one',
        ),
    ]
