# Generated by Django 3.0.6 on 2020-08-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_books_book_brief_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=100)),
                ('upvote', models.CharField(max_length=100)),
                ('downvote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('user_member', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Author'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='books',
            name='published_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=254)),
                ('logged_date', models.DateField(auto_now=True)),
                ('user_profile', models.DateField(auto_now=True)),
                ('user_activity_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.UserActivity')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_time', models.TimeField(auto_now=True)),
                ('book_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Books')),
            ],
        ),
        migrations.AddField(
            model_name='useractivity',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Books'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('book_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Books')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_details_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.BookDetails'),
        ),
    ]
