# Generated by Django 3.0.6 on 2020-09-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200827_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='book_details_id',
            new_name='book_details',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='book_id',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='book_id',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='user_id',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='usercollection',
            old_name='book_id',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_activity_id',
            new_name='user_activity',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='users',
        ),
    ]
